### ISSUE TITLE
problem with install on php 7.1

### ISSUE THREAD

**Issue by directline** [php-cuong/magento2-vietnamese-url-key#1]
Hi, I use magento 2.2, I want to install your extension but i get this error:
`[InvalidArgumentException]
  Could not find package php-cuong/magento2-vietnamese-url-key at any version matching your PHP version 7.1.11.0
`
How can I install your extension?

**Comment by php-cuong** [comment]
@directline The issue was fixed in the version 2.2.0 of this extension.

**Comment by directline** [comment]
thank you, but I test it again but I get the same error.
I think this extension has problem with php version 7.1.11.
`Could not find package php-cuong/magento2-vietnamese-url-key at any version matching your PHP version 7.1.11.0`
